# Generated by Django 4.1.1 on 2022-09-29 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sudo_chat", "0002_rename_room_message_room_name_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="room",
            name="users",
        ),
        migrations.AlterField(
            model_name="message",
            name="username",
            field=models.CharField(max_length=200),
        ),
    ]
