# Generated by Django 4.1.1 on 2022-10-13 06:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("sudo_chat", "0003_remove_room_users_alter_message_username"),
    ]

    operations = [
        migrations.AddField(
            model_name="room",
            name="created_on",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
